
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000 
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env.local
    depends_on:
      - db

  db:
    image: postgres:17
    env_file:
      - .env.local
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
